# services:
#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: frontend.dockerfile
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#     networks:
#       - app-network # 同じネットワークに追加

#   backend:
#     build:
#       context: .
#       dockerfile: backend/backend.dockerfile
#     ports:
#       - "4000:4000"
#       # 変更
#     volumes:
#       - ./backend:/app
#     depends_on:
#       - db
#     networks:
#       - app-network # 同じネットワークに追加

#   db:
#     image: postgres:15
#     environment:
#       POSTGRES_DB: lastProject
#       POSTGRES_USER: lastProject_user
#       POSTGRES_PASSWORD: lastProject
#     ports:
#       - "5433:5432"
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#     networks:
#       - app-network # 同じネットワークに追加

# volumes:
#   pgdata:

# networks:
#   app-network:
#     driver: bridge

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: backend/backend.dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: lastProject
      POSTGRES_USER: lastProject_user
      POSTGRES_PASSWORD: lastProject
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:


networks:
  app-network:
    driver: bridge
