"""Add job_title to jobs table

Revision ID: 1972185a1a9e
Revises: c794516cf0b4
Create Date: 2024-10-20 12:58:38.479769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1972185a1a9e'
down_revision = 'c794516cf0b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        # jobsテーブルにjob_titleカラムを追加するためにnullable=Falseを一度Trueに変更
        batch_op.add_column(sa.Column('job_title', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('job_title')

    # ### end Alembic commands ###
