"""Create union_profiles table

Revision ID: 847c77b92bec
Revises: ae90ac1331b4
Create Date: 2024-10-18 02:02:02.298089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '847c77b92bec'
down_revision = 'ae90ac1331b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('union_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('union_name', sa.String(length=100), nullable=False),
    sa.Column('representative_name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('date_of_foundation', sa.Date(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('union_profiles')
    # ### end Alembic commands ###
