"""Add industry column to jobs table

Revision ID: c794516cf0b4
Revises: bacb8ee8f9bc
Create Date: 2024-10-20 10:11:52.407855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c794516cf0b4'
down_revision = 'bacb8ee8f9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('industry', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('industry')

    # ### end Alembic commands ###
